#
#changed DIR_ROOT
#
export DIR_ROOT=$(shell pwd)/..

#
#don't change it
#
include $(DIR_ROOT)/mk/define.mk

#
#changed me, append sub-system
#
SUB_SYSTEM=blob \
		coroutine \
		dll \
		fd \
		loopc \
		loops \
		mac \
		pipe \
		slice \
		timer \
		zlib \
		#end

#
#don't change it
#
include $(DIR_ROOT)/mk/template.mk