#
#changed DIR_ROOT
#
export DIR_ROOT=$(shell pwd)/..

#
#don't change it
#
include $(DIR_ROOT)/mk/define.mk

#
#changed me, append sub-system
#
SUB_SYSTEM=ak \
		benv \
		bkdr \
		duktape \
		fcookie \
		guard \
		hisi \
		jlogger \
		jlogd \
		nsqa \
		nsqc \
		rsha \
		rt \
		sem \
		sys \
		smc \
		smd \
		tmc \
		tmd \
		umc \
		umd \
		pexec \
		#end

#
#don't change it
#
include $(DIR_ROOT)/mk/template.mk
