#
#changed DIR_ROOT
#
export DIR_ROOT=$(shell pwd)/..

#
#don't change it
#
include $(DIR_ROOT)/mk/define.mk

#
#changed me, append sub-system
#
SUB_SYSTEM=ak bkdr sem rt otp guard benv haenv sys fcookie umc umd tmc tmd smc smd jlogger jlogd duktape

#
#don't change it
#
include $(DIR_ROOT)/mk/template.mk