static const dukc_number_entry_t libcurl_number[] = {
    // BEHAVIOR OPTIONS
    LIB_VALUE(CURLOPT_VERBOSE),
    LIB_VALUE(CURLOPT_HEADER),
    LIB_VALUE(CURLOPT_NOPROGRESS),
#if LIBCURL_VERSION(7, 10, 0)
    LIB_VALUE(CURLOPT_NOSIGNAL),
#endif
#if LIBCURL_VERSION(7, 21, 0)
    LIB_VALUE(CURLOPT_WILDCARDMATCH),
#endif

#if 0
    // CALLBACK OPTIONS
    LIB_VALUE(CURLOPT_WRITEFUNCTION),
    LIB_VALUE(CURLOPT_WRITEDATA),
    LIB_VALUE(CURLOPT_READFUNCTION),
    LIB_VALUE(CURLOPT_READDATA),
    LIB_VALUE(CURLOPT_IOCTLFUNCTION),
    LIB_VALUE(CURLOPT_IOCTLDATA),
    LIB_VALUE(CURLOPT_SEEKFUNCTION),
    LIB_VALUE(CURLOPT_SEEKDATA),
    LIB_VALUE(CURLOPT_SOCKOPTFUNCTION),
    LIB_VALUE(CURLOPT_SOCKOPTDATA),
    LIB_VALUE(CURLOPT_OPENSOCKETFUNCTION),
    LIB_VALUE(CURLOPT_OPENSOCKETDATA),
    LIB_VALUE(CURLOPT_CLOSESOCKETFUNCTION),
    LIB_VALUE(CURLOPT_CLOSESOCKETDATA),
    LIB_VALUE(CURLOPT_PROGRESSFUNCTION),
    LIB_VALUE(CURLOPT_PROGRESSDATA),
    LIB_VALUE(CURLOPT_XFERINFOFUNCTION),
    LIB_VALUE(CURLOPT_XFERINFODATA),
    LIB_VALUE(CURLOPT_HEADERFUNCTION),
    LIB_VALUE(CURLOPT_HEADERDATA),
    LIB_VALUE(CURLOPT_DEBUGFUNCTION),
    LIB_VALUE(CURLOPT_DEBUGDATA),
    LIB_VALUE(CURLOPT_SSL_CTX_FUNCTION),
    LIB_VALUE(CURLOPT_SSL_CTX_DATA),
    LIB_VALUE(CURLOPT_CONV_TO_NETWORK_FUNCTION),
    LIB_VALUE(CURLOPT_CONV_FROM_NETWORK_FUNCTION),
    LIB_VALUE(CURLOPT_CONV_FROM_UTF8_FUNCTION),
    LIB_VALUE(CURLOPT_INTERLEAVEFUNCTION),
    LIB_VALUE(CURLOPT_INTERLEAVEDATA),
    LIB_VALUE(CURLOPT_CHUNK_BGN_FUNCTION),
    LIB_VALUE(CURLOPT_CHUNK_END_FUNCTION),
    LIB_VALUE(CURLOPT_CHUNK_DATA),
    LIB_VALUE(CURLOPT_FNMATCH_FUNCTION),
    LIB_VALUE(CURLOPT_FNMATCH_DATA),
#endif

    // ERROR OPTIONS
    LIB_VALUE(CURLOPT_ERRORBUFFER),
    LIB_VALUE(CURLOPT_STDERR),
    LIB_VALUE(CURLOPT_FAILONERROR),

    // NETWORK OPTIONS
    LIB_VALUE(CURLOPT_URL),
#if LIBCURL_VERSION(7, 42, 0)
    LIB_VALUE(CURLOPT_PATH_AS_IS),
#endif
#if LIBCURL_VERSION(7, 19, 4)
    LIB_VALUE(CURLOPT_PROTOCOLS),
    LIB_VALUE(CURLOPT_REDIR_PROTOCOLS),
#endif
#if LIBCURL_VERSION(7, 45, 0)
    LIB_VALUE(CURLOPT_DEFAULT_PROTOCOL),
#endif
#if LIBCURL_VERSION(7, 21, 7)
    LIB_VALUE(CURLOPT_PROXY),
#endif
    LIB_VALUE(CURLOPT_PROXYPORT),
    LIB_VALUE(CURLOPT_PROXYTYPE),
#if LIBCURL_VERSION(7, 19, 4)
    LIB_VALUE(CURLOPT_NOPROXY),
#endif
    LIB_VALUE(CURLOPT_HTTPPROXYTUNNEL),
#if LIBCURL_VERSION(7, 19, 4)
    LIB_VALUE(CURLOPT_SOCKS5_GSSAPI_SERVICE),
    LIB_VALUE(CURLOPT_SOCKS5_GSSAPI_NEC),
#endif
#if LIBCURL_VERSION(7, 43, 0)
    LIB_VALUE(CURLOPT_PROXY_SERVICE_NAME),
    LIB_VALUE(CURLOPT_SERVICE_NAME),
#endif
    LIB_VALUE(CURLOPT_INTERFACE),
#if LIBCURL_VERSION(7, 15, 2)
    LIB_VALUE(CURLOPT_LOCALPORT),
    LIB_VALUE(CURLOPT_LOCALPORTRANGE),
#endif
    LIB_VALUE(CURLOPT_DNS_CACHE_TIMEOUT),
#if 0 /* Subject for removal in the future. Do not use! */
    LIB_VALUE(CURLOPT_DNS_USE_GLOBAL_CACHE),
#endif
#if LIBCURL_VERSION(7, 10, 0)
    LIB_VALUE(CURLOPT_BUFFERSIZE),
#endif
    LIB_VALUE(CURLOPT_PORT),
    LIB_VALUE(CURLOPT_TCP_NODELAY),
#if LIBCURL_VERSION(7, 19, 0)
    LIB_VALUE(CURLOPT_ADDRESS_SCOPE),
#endif
#if LIBCURL_VERSION(7, 25, 0)
    LIB_VALUE(CURLOPT_TCP_KEEPALIVE),
    LIB_VALUE(CURLOPT_TCP_KEEPIDLE),
#endif
    LIB_VALUE(CURLOPT_TCP_KEEPINTVL),
#if LIBCURL_VERSION(7, 40, 0)
    LIB_VALUE(CURLOPT_UNIX_SOCKET_PATH),
#endif

    // NAMES and PASSWORDS OPTIONS (Authentication)
    LIB_VALUE(CURLOPT_NETRC),
#if LIBCURL_VERSION(7, 10, 9)
    LIB_VALUE(CURLOPT_NETRC_FILE),
#endif
    LIB_VALUE(CURLOPT_USERPWD),
    LIB_VALUE(CURLOPT_PROXYUSERPWD),
#if LIBCURL_VERSION(7, 19, 1)
    LIB_VALUE(CURLOPT_USERNAME),
    LIB_VALUE(CURLOPT_PASSWORD),
#endif
#if LIBCURL_VERSION(7, 34, 0)
    LIB_VALUE(CURLOPT_LOGIN_OPTIONS),
#endif
#if LIBCURL_VERSION(7, 19, 1)
    LIB_VALUE(CURLOPT_PROXYUSERNAME),
    LIB_VALUE(CURLOPT_PROXYPASSWORD),
#endif
#if LIBCURL_VERSION(7, 10, 6)
    LIB_VALUE(CURLOPT_HTTPAUTH),
#endif
#if LIBCURL_VERSION(7, 21, 4)
    LIB_VALUE(CURLOPT_TLSAUTH_USERNAME),
    LIB_VALUE(CURLOPT_TLSAUTH_PASSWORD),
    LIB_VALUE(CURLOPT_TLSAUTH_TYPE),
#endif
#if LIBCURL_VERSION(7, 10, 7)
    LIB_VALUE(CURLOPT_PROXYAUTH),
#endif
#if LIBCURL_VERSION(7, 31, 0)
    LIB_VALUE(CURLOPT_SASL_IR),
#endif
#if LIBCURL_VERSION(7, 33, 0)
    LIB_VALUE(CURLOPT_XOAUTH2_BEARER),
#endif

    // HTTP OPTIONS
    LIB_VALUE(CURLOPT_AUTOREFERER),
#if LIBCURL_VERSION(7, 21, 6)
    LIB_VALUE(CURLOPT_ACCEPT_ENCODING),
#endif
#if LIBCURL_VERSION(7, 21, 6)
    LIB_VALUE(CURLOPT_TRANSFER_ENCODING),
#endif
    LIB_VALUE(CURLOPT_FOLLOWLOCATION),
    LIB_VALUE(CURLOPT_UNRESTRICTED_AUTH),
    LIB_VALUE(CURLOPT_MAXREDIRS),
#if LIBCURL_VERSION(7, 17, 1)
    LIB_VALUE(CURLOPT_POSTREDIR),
#endif
#if 0 /* Deprecated since 7.12.1. Do not use. */
    LIB_VALUE(CURLOPT_PUT),
#endif
    LIB_VALUE(CURLOPT_POST),
    LIB_VALUE(CURLOPT_POSTFIELDS),
    LIB_VALUE(CURLOPT_POSTFIELDSIZE),
    LIB_VALUE(CURLOPT_POSTFIELDSIZE_LARGE),
#if LIBCURL_VERSION(7, 17, 1)
    LIB_VALUE(CURLOPT_COPYPOSTFIELDS),
#endif
    LIB_VALUE(CURLOPT_HTTPPOST),
    LIB_VALUE(CURLOPT_REFERER),
    LIB_VALUE(CURLOPT_USERAGENT),
    LIB_VALUE(CURLOPT_HTTPHEADER),
#if LIBCURL_VERSION(7, 37, 0)
    LIB_VALUE(CURLOPT_HEADEROPT),
    LIB_VALUE(CURLOPT_PROXYHEADER),
#endif
#if LIBCURL_VERSION(7, 10, 3)
    LIB_VALUE(CURLOPT_HTTP200ALIASES),
#endif
    LIB_VALUE(CURLOPT_COOKIE),
    LIB_VALUE(CURLOPT_COOKIEFILE),
    LIB_VALUE(CURLOPT_COOKIEJAR),
    LIB_VALUE(CURLOPT_COOKIESESSION),
#if LIBCURL_VERSION(7, 39, 0)
    LIB_VALUE(CURLOPT_COOKIELIST),
#endif
    LIB_VALUE(CURLOPT_HTTPGET),
    LIB_VALUE(CURLOPT_HTTP_VERSION),
#if LIBCURL_VERSION(7, 14, 1)
    LIB_VALUE(CURLOPT_IGNORE_CONTENT_LENGTH),
#endif
#if LIBCURL_VERSION(7, 16, 2)
    LIB_VALUE(CURLOPT_HTTP_CONTENT_DECODING),
    LIB_VALUE(CURLOPT_HTTP_TRANSFER_DECODING),
#endif
#if LIBCURL_VERSION(7, 36, 0)
    LIB_VALUE(CURLOPT_EXPECT_100_TIMEOUT_MS),
#endif
#if LIBCURL_VERSION(7, 43, 0)
    LIB_VALUE(CURLOPT_PIPEWAIT),
#endif
#if LIBCURL_VERSION(7, 46, 0)
    LIB_VALUE(CURLOPT_STREAM_DEPENDS),
    LIB_VALUE(CURLOPT_STREAM_DEPENDS_E),
    LIB_VALUE(CURLOPT_STREAM_WEIGHT),
#endif

    // SMTP OPTIONS
#if LIBCURL_VERSION(7, 20, 0)
    LIB_VALUE(CURLOPT_MAIL_FROM),
    LIB_VALUE(CURLOPT_MAIL_RCPT),
#endif
#if LIBCURL_VERSION(7, 25, 0)
    LIB_VALUE(CURLOPT_MAIL_AUTH),
#endif

    // TFTP OPTIONS
#if LIBCURL_VERSION(7, 19, 4)
    LIB_VALUE(CURLOPT_TFTP_BLKSIZE),
#endif
#if LIBCURL_VERSION(7, 48, 0)
    LIB_VALUE(CURLOPT_TFTP_NO_OPTIONS),
#endif

    // FTP OPTIONS
#if LIBCURL_VERSION(7, 19, 5)
    LIB_VALUE(CURLOPT_FTPPORT),
#endif
#if LIBCURL_VERSION(7, 24, 0)
    LIB_VALUE(CURLOPT_QUOTE),
#endif
    LIB_VALUE(CURLOPT_POSTQUOTE),
    LIB_VALUE(CURLOPT_PREQUOTE),
#if LIBCURL_VERSION(7, 16, 4)
    LIB_VALUE(CURLOPT_APPEND),
#endif
#if LIBCURL_VERSION(7, 10, 5)
    LIB_VALUE(CURLOPT_FTP_USE_EPRT),
#endif
    LIB_VALUE(CURLOPT_FTP_USE_EPSV),
#if LIBCURL_VERSION(7, 20, 0)
    LIB_VALUE(CURLOPT_FTP_USE_PRET),
#endif
#if LIBCURL_VERSION(7, 19, 4)
    LIB_VALUE(CURLOPT_FTP_CREATE_MISSING_DIRS),
#endif
#if LIBCURL_VERSION(7, 10, 8)
    LIB_VALUE(CURLOPT_FTP_RESPONSE_TIMEOUT),
#endif
#if LIBCURL_VERSION(7, 15, 5)
    LIB_VALUE(CURLOPT_FTP_ALTERNATIVE_TO_USER),
#endif
#if LIBCURL_VERSION(7, 14, 2)
    LIB_VALUE(CURLOPT_FTP_SKIP_PASV_IP),
#endif
#if LIBCURL_VERSION(7, 12, 2)
    LIB_VALUE(CURLOPT_FTPSSLAUTH),
#endif
#if LIBCURL_VERSION(7, 16, 1)
    LIB_VALUE(CURLOPT_FTP_SSL_CCC),
#endif
#if LIBCURL_VERSION(7, 13, 0)
    LIB_VALUE(CURLOPT_FTP_ACCOUNT),
#endif
#if LIBCURL_VERSION(7, 15, 1)
    LIB_VALUE(CURLOPT_FTP_FILEMETHOD),
#endif

    // RTSP OPTIONS
#if LIBCURL_VERSION(7, 20, 0)
    LIB_VALUE(CURLOPT_RTSP_REQUEST),
    LIB_VALUE(CURLOPT_RTSP_SESSION_ID),
    LIB_VALUE(CURLOPT_RTSP_STREAM_URI),
    LIB_VALUE(CURLOPT_RTSP_TRANSPORT),
    LIB_VALUE(CURLOPT_RTSP_CLIENT_CSEQ),
    LIB_VALUE(CURLOPT_RTSP_SERVER_CSEQ),
#endif

    // PROTOCOL OPTIONS
    LIB_VALUE(CURLOPT_TRANSFERTEXT),
#if LIBCURL_VERSION(7, 18, 0)
    LIB_VALUE(CURLOPT_PROXY_TRANSFER_MODE),
#endif
#if LIBCURL_VERSION(7, 40, 0)
    LIB_VALUE(CURLOPT_CRLF),
#endif
#if LIBCURL_VERSION(7, 18, 0)
    LIB_VALUE(CURLOPT_RANGE),
#endif
    LIB_VALUE(CURLOPT_RESUME_FROM),
#if LIBCURL_VERSION(7, 11, 0)
    LIB_VALUE(CURLOPT_RESUME_FROM_LARGE),
#endif
#if LIBCURL_VERSION(7, 34, 0)
    LIB_VALUE(CURLOPT_CUSTOMREQUEST),
#endif
    LIB_VALUE(CURLOPT_FILETIME),
#if LIBCURL_VERSION(7, 16, 4)
    LIB_VALUE(CURLOPT_DIRLISTONLY),
#endif
    LIB_VALUE(CURLOPT_NOBODY),
#if LIBCURL_VERSION(7, 23, 0)
    LIB_VALUE(CURLOPT_INFILESIZE),
    LIB_VALUE(CURLOPT_INFILESIZE_LARGE),
#endif
    LIB_VALUE(CURLOPT_UPLOAD),
    LIB_VALUE(CURLOPT_UPLOAD),
#if LIBCURL_VERSION(7, 11, 0)
    LIB_VALUE(CURLOPT_MAXFILESIZE_LARGE),
#endif
    LIB_VALUE(CURLOPT_TIMECONDITION),
    LIB_VALUE(CURLOPT_TIMEVALUE),

    // CONNECTION OPTIONS
    LIB_VALUE(CURLOPT_TIMEOUT),
    LIB_VALUE(CURLOPT_TIMEOUT_MS),
    LIB_VALUE(CURLOPT_LOW_SPEED_LIMIT),
    LIB_VALUE(CURLOPT_LOW_SPEED_TIME),
#if LIBCURL_VERSION(7, 15, 5)
    LIB_VALUE(CURLOPT_MAX_SEND_SPEED_LARGE),
    LIB_VALUE(CURLOPT_MAX_RECV_SPEED_LARGE),
#endif
    LIB_VALUE(CURLOPT_MAXCONNECTS),
    LIB_VALUE(CURLOPT_FRESH_CONNECT),
    LIB_VALUE(CURLOPT_FORBID_REUSE),
    LIB_VALUE(CURLOPT_CONNECTTIMEOUT),
    LIB_VALUE(CURLOPT_CONNECTTIMEOUT_MS),
    LIB_VALUE(CURLOPT_IPRESOLVE),
#if LIBCURL_VERSION(7, 15, 2)
    LIB_VALUE(CURLOPT_CONNECT_ONLY),
#endif
#if LIBCURL_VERSION(7, 11, 0)
    LIB_VALUE(CURLOPT_USE_SSL),
#endif
#if LIBCURL_VERSION(7, 21, 3)
    LIB_VALUE(CURLOPT_RESOLVE),
#endif
#if LIBCURL_VERSION(7, 33, 0)
    LIB_VALUE(CURLOPT_DNS_INTERFACE),
    LIB_VALUE(CURLOPT_DNS_LOCAL_IP4),
    LIB_VALUE(CURLOPT_DNS_LOCAL_IP6),
#endif
#if LIBCURL_VERSION(7, 24, 0)
    LIB_VALUE(CURLOPT_DNS_SERVERS),
    LIB_VALUE(CURLOPT_ACCEPTTIMEOUT_MS),
#endif

    // SSL and SECURITY OPTIONS
    LIB_VALUE(CURLOPT_SSLCERT),
#if LIBCURL_VERSION(7, 9, 3)
    LIB_VALUE(CURLOPT_SSLCERTTYPE),
#endif
    LIB_VALUE(CURLOPT_SSLKEY),
    LIB_VALUE(CURLOPT_SSLKEYTYPE),
#if LIBCURL_VERSION(7, 16, 4)
    LIB_VALUE(CURLOPT_KEYPASSWD),
#endif
#if LIBCURL_VERSION(7, 36, 0)
    LIB_VALUE(CURLOPT_SSL_ENABLE_ALPN),
    LIB_VALUE(CURLOPT_SSL_ENABLE_NPN),
#endif
    LIB_VALUE(CURLOPT_SSLENGINE),
    LIB_VALUE(CURLOPT_SSLENGINE_DEFAULT),
#if LIBCURL_VERSION(7, 42, 0)
    LIB_VALUE(CURLOPT_SSL_FALSESTART),
#endif
#if LIBCURL_VERSION(7, 18, 1)
    LIB_VALUE(CURLOPT_SSLVERSION),
#endif
    LIB_VALUE(CURLOPT_SSL_VERIFYHOST),
    LIB_VALUE(CURLOPT_SSL_VERIFYPEER),
#if LIBCURL_VERSION(7, 41, 0)
    LIB_VALUE(CURLOPT_SSL_VERIFYSTATUS),
#endif
    LIB_VALUE(CURLOPT_CAINFO),
    LIB_VALUE(CURLOPT_ISSUERCERT),
    LIB_VALUE(CURLOPT_CAPATH),
#if LIBCURL_VERSION(7, 19, 0)
    LIB_VALUE(CURLOPT_CRLFILE),
#endif
    LIB_VALUE(CURLOPT_CERTINFO),
#if LIBCURL_VERSION(7, 39, 0)
    LIB_VALUE(CURLOPT_PINNEDPUBLICKEY),
#endif
    LIB_VALUE(CURLOPT_RANDOM_FILE),
    LIB_VALUE(CURLOPT_EGDSOCKET),
    LIB_VALUE(CURLOPT_SSL_CIPHER_LIST),
#if LIBCURL_VERSION(7, 16, 0)
    LIB_VALUE(CURLOPT_SSL_SESSIONID_CACHE),
#endif
#if LIBCURL_VERSION(7, 25, 0)
    LIB_VALUE(CURLOPT_SSL_OPTIONS),
#endif
#if LIBCURL_VERSION(7, 16, 3)
    LIB_VALUE(CURLOPT_KRBLEVEL),
#endif
#if LIBCURL_VERSION(7, 22, 0)
    LIB_VALUE(CURLOPT_GSSAPI_DELEGATION),
#endif

    // SSH OPTIONS
#if LIBCURL_VERSION(7, 28, 0)
    LIB_VALUE(CURLOPT_SSH_AUTH_TYPES),
#endif
#if LIBCURL_VERSION(7, 17, 1)
    LIB_VALUE(CURLOPT_SSH_HOST_PUBLIC_KEY_MD5),
#endif
#if LIBCURL_VERSION(7, 26, 0)
    LIB_VALUE(CURLOPT_SSH_PUBLIC_KEYFILE),
#endif
#if LIBCURL_VERSION(7, 16, 1)
    LIB_VALUE(CURLOPT_SSH_PRIVATE_KEYFILE),
#endif
#if LIBCURL_VERSION(7, 19, 6)
    LIB_VALUE(CURLOPT_SSH_KNOWNHOSTS),
    LIB_VALUE(CURLOPT_SSH_KEYFUNCTION),
    LIB_VALUE(CURLOPT_SSH_KEYDATA),
#endif

    // OTHER OPTIONS
#if LIBCURL_VERSION(7, 10, 3)
    LIB_VALUE(CURLOPT_PRIVATE),
#endif
    LIB_VALUE(CURLOPT_SHARE),
#if LIBCURL_VERSION(7, 16, 4)
    LIB_VALUE(CURLOPT_NEW_FILE_PERMS),
    LIB_VALUE(CURLOPT_NEW_DIRECTORY_PERMS),
#endif
    // TELNET OPTIONS
    LIB_VALUE(CURLOPT_TELNETOPTIONS),

    // RETURN VALUE
    LIB_VALUE(CURLE_OK),
    LIB_VALUE(CURLE_UNSUPPORTED_PROTOCOL),
    LIB_VALUE(CURLE_FAILED_INIT),
    LIB_VALUE(CURLE_URL_MALFORMAT),
    LIB_VALUE(CURLE_NOT_BUILT_IN),
    LIB_VALUE(CURLE_COULDNT_RESOLVE_PROXY),
    LIB_VALUE(CURLE_COULDNT_RESOLVE_HOST),
    LIB_VALUE(CURLE_COULDNT_CONNECT),
    LIB_VALUE(CURLE_FTP_WEIRD_SERVER_REPLY),
    LIB_VALUE(CURLE_REMOTE_ACCESS_DENIED),
    LIB_VALUE(CURLE_FTP_ACCEPT_FAILED),
    LIB_VALUE(CURLE_FTP_WEIRD_PASS_REPLY),
    LIB_VALUE(CURLE_FTP_ACCEPT_TIMEOUT),
    LIB_VALUE(CURLE_FTP_WEIRD_PASV_REPLY),
    LIB_VALUE(CURLE_FTP_WEIRD_227_FORMAT),
    LIB_VALUE(CURLE_FTP_CANT_GET_HOST),
    LIB_VALUE(CURLE_HTTP2),
    LIB_VALUE(CURLE_FTP_COULDNT_SET_TYPE),
    LIB_VALUE(CURLE_PARTIAL_FILE),
    LIB_VALUE(CURLE_FTP_COULDNT_RETR_FILE),
    LIB_VALUE(CURLE_QUOTE_ERROR),
    LIB_VALUE(CURLE_HTTP_RETURNED_ERROR),
    LIB_VALUE(CURLE_WRITE_ERROR),
    LIB_VALUE(CURLE_UPLOAD_FAILED),
    LIB_VALUE(CURLE_READ_ERROR),
    LIB_VALUE(CURLE_OUT_OF_MEMORY),
    LIB_VALUE(CURLE_OPERATION_TIMEDOUT),
    LIB_VALUE(CURLE_FTP_PORT_FAILED),
    LIB_VALUE(CURLE_FTP_COULDNT_USE_REST),
    LIB_VALUE(CURLE_RANGE_ERROR),
    LIB_VALUE(CURLE_HTTP_POST_ERROR),
    LIB_VALUE(CURLE_SSL_CONNECT_ERROR),
    LIB_VALUE(CURLE_BAD_DOWNLOAD_RESUME),
    LIB_VALUE(CURLE_FILE_COULDNT_READ_FILE),
    LIB_VALUE(CURLE_LDAP_CANNOT_BIND),
    LIB_VALUE(CURLE_LDAP_SEARCH_FAILED),
    LIB_VALUE(CURLE_FUNCTION_NOT_FOUND),
    LIB_VALUE(CURLE_ABORTED_BY_CALLBACK),
    LIB_VALUE(CURLE_BAD_FUNCTION_ARGUMENT),
    LIB_VALUE(CURLE_INTERFACE_FAILED),
    LIB_VALUE(CURLE_TOO_MANY_REDIRECTS),
    LIB_VALUE(CURLE_UNKNOWN_OPTION),
    LIB_VALUE(CURLE_TELNET_OPTION_SYNTAX),
    LIB_VALUE(CURLE_PEER_FAILED_VERIFICATION),
    LIB_VALUE(CURLE_GOT_NOTHING),
    LIB_VALUE(CURLE_SSL_ENGINE_NOTFOUND),
    LIB_VALUE(CURLE_SSL_ENGINE_SETFAILED),
    LIB_VALUE(CURLE_SEND_ERROR),
    LIB_VALUE(CURLE_RECV_ERROR),
    LIB_VALUE(CURLE_SSL_CERTPROBLEM),
    LIB_VALUE(CURLE_SSL_CIPHER),
    LIB_VALUE(CURLE_SSL_CACERT),
    LIB_VALUE(CURLE_BAD_CONTENT_ENCODING),
    LIB_VALUE(CURLE_LDAP_INVALID_URL),
    LIB_VALUE(CURLE_FILESIZE_EXCEEDED),
    LIB_VALUE(CURLE_USE_SSL_FAILED),
    LIB_VALUE(CURLE_SEND_FAIL_REWIND),
    LIB_VALUE(CURLE_SSL_ENGINE_INITFAILED),
#if LIBCURL_VERSION(7, 13, 1)
    LIB_VALUE(CURLE_LOGIN_DENIED),
#endif
    LIB_VALUE(CURLE_TFTP_NOTFOUND),
    LIB_VALUE(CURLE_TFTP_PERM),
    LIB_VALUE(CURLE_REMOTE_DISK_FULL),
    //LIB_VALUE(CURLE_TFTP_ILLEGAL),
    LIB_VALUE(CURLE_TFTP_UNKNOWNID),
    LIB_VALUE(CURLE_REMOTE_FILE_EXISTS),
    LIB_VALUE(CURLE_TFTP_NOSUCHUSER),
    //LIB_VALUE(CURLE_CONV_FAILED),
    LIB_VALUE(CURLE_CONV_REQD),
    LIB_VALUE(CURLE_SSL_CACERT_BADFILE),
    LIB_VALUE(CURLE_REMOTE_FILE_NOT_FOUND),
    LIB_VALUE(CURLE_SSH),
    LIB_VALUE(CURLE_SSL_SHUTDOWN_FAILED),
#if LIBCURL_VERSION(7, 18, 2)
    LIB_VALUE(CURLE_AGAIN),
#endif
#if LIBCURL_VERSION(7, 19, 0)
    LIB_VALUE(CURLE_SSL_CRL_BADFILE),
    LIB_VALUE(CURLE_SSL_ISSUER_ERROR),
#endif
#if LIBCURL_VERSION(7, 20, 0)
    LIB_VALUE(CURLE_FTP_PRET_FAILED),
#endif
    LIB_VALUE(CURLE_RTSP_CSEQ_ERROR),
    LIB_VALUE(CURLE_RTSP_SESSION_ERROR),
    LIB_VALUE(CURLE_FTP_BAD_FILE_LIST),
    LIB_VALUE(CURLE_CHUNK_FAILED),
#if LIBCURL_VERSION(7, 30, 0)
    LIB_VALUE(CURLE_NO_CONNECTION_AVAILABLE),
#endif
#if LIBCURL_VERSION(7, 39, 0)
    LIB_VALUE(CURLE_SSL_PINNEDPUBKEYNOTMATCH),
#endif
#if LIBCURL_VERSION(7, 41, 0)
    LIB_VALUE(CURLE_SSL_INVALIDCERTSTATUS),
#endif

    LIB_VALUE(CURL_ERROR_SIZE),

#if LIBCURL_VERSION(7, 19, 4)
    LIB_VALUE(CURLPROTO_DICT),
    LIB_VALUE(CURLPROTO_FILE),
    LIB_VALUE(CURLPROTO_FTP),
    LIB_VALUE(CURLPROTO_FTPS),
    LIB_VALUE(CURLPROTO_GOPHER),
    LIB_VALUE(CURLPROTO_HTTP),
    LIB_VALUE(CURLPROTO_HTTPS),
    LIB_VALUE(CURLPROTO_IMAP),
    LIB_VALUE(CURLPROTO_IMAPS),
    LIB_VALUE(CURLPROTO_LDAP),
    LIB_VALUE(CURLPROTO_LDAPS),
    LIB_VALUE(CURLPROTO_POP3),
    LIB_VALUE(CURLPROTO_POP3S),
    LIB_VALUE(CURLPROTO_RTMP),
    LIB_VALUE(CURLPROTO_RTMPE),
    LIB_VALUE(CURLPROTO_RTMPS),
    LIB_VALUE(CURLPROTO_RTMPT),
    LIB_VALUE(CURLPROTO_RTMPTE),
    LIB_VALUE(CURLPROTO_RTMPTS),
    LIB_VALUE(CURLPROTO_RTSP),
    LIB_VALUE(CURLPROTO_SCP),
    LIB_VALUE(CURLPROTO_SFTP),
#if LIBCURL_VERSION(7, 40, 0)
    LIB_VALUE(CURLPROTO_SMB),
    LIB_VALUE(CURLPROTO_SMBS),
#endif
    LIB_VALUE(CURLPROTO_SMTP),
    LIB_VALUE(CURLPROTO_SMTPS),
    LIB_VALUE(CURLPROTO_TELNET),
    LIB_VALUE(CURLPROTO_TFTP),
#endif

#if LIBCURL_VERSION(7, 10, 6)
    LIB_VALUE(CURLAUTH_BASIC),
    LIB_VALUE(CURLAUTH_DIGEST),
#if LIBCURL_VERSION(7, 19, 3)
    LIB_VALUE(CURLAUTH_DIGEST_IE),
#endif
    LIB_VALUE(CURLAUTH_NEGOTIATE),
    LIB_VALUE(CURLAUTH_NTLM),
#if LIBCURL_VERSION(7, 22, 0)
    LIB_VALUE(CURLAUTH_NTLM_WB),
#endif
    LIB_VALUE(CURLAUTH_ANY),
    LIB_VALUE(CURLAUTH_ANYSAFE),
#if LIBCURL_VERSION(7, 21, 3)
    LIB_VALUE(CURLAUTH_ONLY),
#endif
#endif

#if LIBCURL_VERSION(7, 17, 1)
    LIB_VALUE(CURL_REDIR_POST_301),
    LIB_VALUE(CURL_REDIR_POST_302),
#if LIBCURL_VERSION(7, 26, 0)
    LIB_VALUE(CURL_REDIR_POST_303),
    LIB_VALUE(CURL_REDIR_POST_ALL),
#endif
#endif

    LIB_VALUE(CURLFORM_COPYNAME),
    LIB_VALUE(CURLFORM_PTRNAME),
    LIB_VALUE(CURLFORM_NAMELENGTH),
    LIB_VALUE(CURLFORM_COPYCONTENTS),
    LIB_VALUE(CURLFORM_PTRCONTENTS),
    //LIB_VALUE(CURLFORM_CONTENTLEN),
    LIB_VALUE(CURLFORM_CONTENTSLENGTH),
    LIB_VALUE(CURLFORM_FILECONTENT),
    LIB_VALUE(CURLFORM_FILE),
    LIB_VALUE(CURLFORM_CONTENTTYPE),
    LIB_VALUE(CURLFORM_FILENAME),
    LIB_VALUE(CURLFORM_BUFFER),
    LIB_VALUE(CURLFORM_BUFFERPTR),
    LIB_VALUE(CURLFORM_BUFFERLENGTH),
    LIB_VALUE(CURLFORM_STREAM),
    LIB_VALUE(CURLFORM_ARRAY),
    LIB_VALUE(CURLFORM_END),
    LIB_VALUE(CURLFORM_CONTENTHEADER),
    
    LIB_VALUE(CURL_HTTP_VERSION_NONE),
    LIB_VALUE(CURL_HTTP_VERSION_1_0),
    LIB_VALUE(CURL_HTTP_VERSION_1_1),
    LIB_VALUE(CURL_HTTP_VERSION_2_0),
    //LIB_VALUE(CURL_HTTP_VERSION_2TLS),

    LIB_VALUE(CURLFTP_CREATE_DIR_NONE),
    LIB_VALUE(CURLFTP_CREATE_DIR),
    LIB_VALUE(CURLFTP_CREATE_DIR_RETRY),
    
    LIB_VALUE(CURLFTPAUTH_DEFAULT),
    LIB_VALUE(CURLFTPAUTH_SSL),
    LIB_VALUE(CURLFTPAUTH_TLS),
    
    LIB_VALUE(CURLFTPSSL_CCC_NONE),
    LIB_VALUE(CURLFTPSSL_CCC_PASSIVE),
    LIB_VALUE(CURLFTPSSL_CCC_ACTIVE),
    
    LIB_VALUE(CURLFTPMETHOD_MULTICWD),
    LIB_VALUE(CURLFTPMETHOD_NOCWD),
    LIB_VALUE(CURLFTPMETHOD_SINGLECWD),
    
    LIB_VALUE(CURL_RTSPREQ_OPTIONS),
    LIB_VALUE(CURL_RTSPREQ_DESCRIBE),
    LIB_VALUE(CURL_RTSPREQ_ANNOUNCE),
    LIB_VALUE(CURL_RTSPREQ_SETUP),
    LIB_VALUE(CURL_RTSPREQ_PLAY),
    LIB_VALUE(CURL_RTSPREQ_PAUSE),
    LIB_VALUE(CURL_RTSPREQ_TEARDOWN),
    LIB_VALUE(CURL_RTSPREQ_GET_PARAMETER),
    LIB_VALUE(CURL_RTSPREQ_SET_PARAMETER),
    LIB_VALUE(CURL_RTSPREQ_RECORD),
    LIB_VALUE(CURL_RTSPREQ_RECEIVE),
    
    LIB_VALUE(CURL_TIMECOND_IFMODSINCE),
    LIB_VALUE(CURL_TIMECOND_IFUNMODSINCE),
    
    LIB_VALUE(CURL_IPRESOLVE_WHATEVER),
    LIB_VALUE(CURL_IPRESOLVE_V4),
    LIB_VALUE(CURL_IPRESOLVE_V6),
    
    LIB_VALUE(CURLUSESSL_NONE),
    LIB_VALUE(CURLUSESSL_TRY),
    LIB_VALUE(CURLUSESSL_CONTROL),
    LIB_VALUE(CURLUSESSL_ALL),
    
    LIB_VALUE(CURL_SSLVERSION_DEFAULT),
    LIB_VALUE(CURL_SSLVERSION_TLSv1),
    LIB_VALUE(CURL_SSLVERSION_SSLv2),
    LIB_VALUE(CURL_SSLVERSION_SSLv3),
    LIB_VALUE(CURL_SSLVERSION_TLSv1_0),
    LIB_VALUE(CURL_SSLVERSION_TLSv1_1),
    LIB_VALUE(CURL_SSLVERSION_TLSv1_2),
    
    LIB_VALUE(CURLSSLOPT_ALLOW_BEAST),
    // LIB_VALUE(CURLSSLOPT_NO_REVOKE),
    
    LIB_VALUE(CURLGSSAPI_DELEGATION_FLAG),
    LIB_VALUE(CURLGSSAPI_DELEGATION_POLICY_FLAG),
    LIB_VALUE(CURLGSSAPI_DELEGATION_NONE),
    
    LIB_VALUE(CURLSSH_AUTH_ANY),
    LIB_VALUE(CURLSSH_AUTH_NONE),
    LIB_VALUE(CURLSSH_AUTH_PUBLICKEY),
    LIB_VALUE(CURLSSH_AUTH_PASSWORD),
    LIB_VALUE(CURLSSH_AUTH_HOST),
    LIB_VALUE(CURLSSH_AUTH_KEYBOARD),
    LIB_VALUE(CURLSSH_AUTH_AGENT),
    LIB_VALUE(CURLSSH_AUTH_DEFAULT),
    
    LIB_VALUE_END
};

static void
libcurln_register(duk_context *ctx, duk_idx_t idx)
{
    duk_put_number_list(ctx, idx, libcurl_number);
}

